# syntax - https://github.com/redhat-plumbers-in-action/advanced-issue-labeler#policy
---

policy:
  - template: [bug.yml]
    section:
      - id: [frequency]
        label:
          - name: 'Frequency:Once'
            keys: ['Once']
          - name: 'Frequency:Sometimes'
            keys: ['Sometimes']
          - name: 'Frequency:Allways'
            keys: ['Allways']

      - id: [repro]
        label:
          - name: 'Repro:Always'
            keys: ['Always']
          - name: 'Repro:Sometimes'
            keys: ['Sometimes']
          - name: 'Repro:No'
            keys: ['No']

      - id: [sync, flavour]
        block-list: []
        label:
          - name: 'SDK-Use:Local'
            keys: [Local Database only']
          - name: 'SDK-Use:Sync' 
            keys: ['Atlas Device Sync']
          - name: 'SDK-Use:Services'
            keys: [
              'Atlas App Services (auth, functions, etc.)',
              'MongoDB Atlas (Sync or auth or functions)',
              'MongoDB Realm (i.e. Sync, auth, functions)'
              ]

      - id: [encryption]
        block-list: []
        label:
          - name: 'Encryption:On'
            keys: ['Yes']
          - name: 'Encryption:Off'
            keys: ['No']
            
       - id: [app-type]
         label:
          - name: 'App-type:Unity'
            keys: ['Unity']
          - name: 'App-type:Xamarin'
            keys: ['Xamarin']
          - name: 'App-type:WPF'
            keys: ['WPF']
          - name: 'App-type:Console/Server'
            keys: ['Console/Server']
          - name: 'App-type:Other'
            keys: ['Other']
