# syntax - https://github.com/redhat-plumbers-in-action/advanced-issue-labeler#policy
---

policy:
  - template: [bug-freq.yml]
    section:
      - id: [frequency]
        block-list: ['None']
        label:
          - name: 'Seen-once'
            keys: ['Frequency: Once']
          - name: 'Sometimes'
            keys: ['Frequency: Sometimes']
