# syntax - https://github.com/redhat-plumbers-in-action/advanced-issue-labeler#policy
---

policy:
  - template: [bug.yml, feature.yml]
    section:
      - id: [frequency]
        label:
          - name: 'Frequency:Once'
            keys: ['Once']
          - name: 'Frequency:Sometimes'
            keys: ['Sometimes']
          - name: 'Frequency:Allways'
            keys: ['Allways']

      - id: [repro]
        label:
          - name: 'Repro:Always'
            keys: ['Always']
          - name: 'Repro:Sometimes'
            keys: ['Sometimes']
          - name: 'Repro:No'
            keys: ['No']

      - id: [sync, flavour, services]
        block-list: []
        label:
          - name: 'SDK-Use:Local'
            keys: ['Local Database only']
          - name: 'SDK-Use:Sync' 
            keys: ['Atlas Device Sync']
          - name: 'SDK-Use:Services'
            keys: ['Atlas App Services: Auth or Functions etc']
          - name: ['SDK-Use:All']
            keys: ['Both Atlas Device Sync and Atlas App Services']

      - id: [encryption]
        block-list: []
        label:
          - name: 'Encryption:On'
            keys: ['Yes']
          - name: 'Encryption:Off'
            keys: ['No']
            
      - id: [app-type]
        block-list: []
        label:
          - name: 'App-type:Unity'
            keys: ['Unity']
          - name: 'App-type:Xamarin'
            keys: ['Xamarin']
          - name: 'App-type:WPF'
            keys: ['WPF']
          - name: 'App-type:Console/Server'
            keys: ['Console/Server']
          - name: 'App-type:Other'
            keys: ['Other']
           
      - id: [importance]
        block-list: []
        label:
          - name: 'Importance:Dealbraker'
            keys: ['Dealbraker']
          - name: 'Importance:Dealbraker'
            keys: ['Would be a major improvement']
          - name: 'Importance:Workaround'
            keys: ['I'd like to see it but have a workaround']
          - name: 'Importance:Nice'
            keys: ['Fairly niche but nice to have anyway']  
