# syntax - https://github.com/redhat-plumbers-in-action/advanced-issue-labeler#policy
---

policy:
  - template: [bug-freq.yml]
    section:
      - id: [frequency]
        block-list: []
        label:
          - name: 'Frequency:Once'
            keys: ['Seen once']
          - name: 'Frequency:Sometimes'
            keys: ['Sometimes']
          - name: 'Frequency:Allways'
            keys: ['All the time']

      - id: [repro]
       block-list: []
        label:
          - name: 'Repro:Always'
            keys: ['Yes, always']
          - name: 'Repro:Sometimes'
            keys: ['Yes, sometimes']
          - name: 'Repro:No'
            keys: ['Not yet']

      - id: [sync, flavour]
        block-list: []
        label:
          - name: 'SDK-Flavour:Local'
            keys: [Local Database only']
          - name: 'SDK:Flavour:Sync' 
            keys: ['Atlas Device Sync']
          - name: 'SDK:Flavour:Services'
            keys: ['Atlas App Services (auth, functions, etc.)',
                   'MongoDB Atlas (i.e. Sync, auth, functions)',
                   'MongoDB Realm (i.e. Sync, auth, functions)']

      - id: [encryption]
        block-list: []
        label:
          - name: 'Encryption:On'
            keys: ['Yes, using encryption']
          - name: 'Encryption:Off'
            keys: ['No, not using encryption']
