# syntax - https://github.com/redhat-plumbers-in-action/advanced-issue-labeler#policy
---

policy:
  - template: [bug.yml]
    section:
      - id: [frequency]
        block-list: []
        label:
          - name: 'Frequency:Once'
            keys: ['Seen_once']
          - name: 'Frequency:Sometimes'
            keys: ['Sometimes']
          - name: 'Frequency:Allways'
            keys: ['All_the_time']

      - id: [repro]
        block-list: []
        label:
          - name: 'Repro:Always'
            keys: ['Yes_always']
          - name: 'Repro:Sometimes'
            keys: ['Yes_sometimes']
          - name: 'Repro:No'
            keys: ['Not_yet']

      - id: [sync, flavour]
        block-list: []
        label:
          - name: 'SDK-Flavour:Local'
            keys: [Local_Database_only']
          - name: 'SDK-Flavour:Sync' 
            keys: ['Atlas_Device_Sync']
          - name: 'SDK-Flavour:Services'
            keys: [
              'Atlas_App_Services', #  (auth, functions, etc.)',
              'MongoDB_Atlas' #  (i.e. Sync, auth, functions)',
              'MongoDB_Realm' # (i.e. Sync, auth, functions)'
              ]

      - id: [encryption]
        block-list: []
        label:
          - name: 'Encryption:On'
            keys: ['Yes_using_encryption']
          - name: 'Encryption:Off'
            keys: ['No_not_using_encryption']
