name: Bug Freq Report
description: Report a bug w Freq
body:
  - type: dropdown
    id: frequency
    attributes:
      label: How often?
      description: Hi
      multiple: false
      options:
        - Choose!
        - Seen once
        - Sometimes
        - All the time
    validations:
      required: true
