name: Bug Report
description: Report a bug
labels: [T-Bug]
body:
  - type: markdown
    attributes:
      value: |
        Please provide as much detail as you can so we have a better chance of fixing the bug quickly. 
        Thanks for your contribution to improve this project!
# "Severity"
  - type: dropdown
    id: frequency
    attributes:
      label: How frequently does the bug occur?
      options:
        - Seen once
        - Rarely
        - Very frequently
        - All the time
    validations:
      required: true
  - type: dropdown
    id: where
    attributes:
      label: Where does the bug occur?
      options:
        - Locally during development or testing
        - In production
    validations:
      required: true 
# Description
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe what you were expecting and what actually happened.
        How is it clear to you this is a bug in Realm and not your application?
    validations:
      required: true
  - type: textarea
    id: stacktrace
    attributes:
      label: Stacktrace & log output
      description: If you're getting an exception/crash, please paste the stacktrace and/or any relevant log output.
      render: shell
# Repro information
  - type: dropdown
    id: repro
    attributes:
      label: Can you reproduce the bug?
      options:
        - Yes, always
        - Yes, sometimes
        - Not yet
    validations:
      required: true 
  - type: textarea
    id: code-snippets
    attributes:
      label: Code snippets
      description: |
        Ideally, please provide a self contained test case or link (e.g. github repo) to a sample app that demonstrates the bug.
        If that's not possible, please show code samples that highlights or reproduce the issue.
        If relevant, include your model definitions.
        Should you need to share code confidentially, you can send a link to: realm-help (the @) mongodb.com.
  - type: textarea
    id: repro-steps
    attributes:
      label: Reproduction steps
      description: |
        If you can reproduce the bug, please provide detailed steps for how WE can reproduce it with the code above.
  - type: textarea
    id: debugging-done
    attributes:
      label: Debugging done
      description: |
        Please describe the debugging you have already done and your analysis of that.
        I.e. have you tried to use the latest version?
# SDK 
  - type: input
    id: version
    attributes:
      label: Version
      description: What version(s) of the SDK has the bug been observed in?
    validations:
      required: true
  - type: dropdown
    id: sync
    attributes:
      label: What SDK flavour are you using?
      options:
        - Local Database only
        - MongoDB Realm (i.e. Sync, auth, functions)
    validations:
      required: true
# Environment
  - type: input
    id: platform
    attributes:
      label: Platform OS and version(s)
      description: OS and version(s) are you seeing the issue on?
    validations:
      required: true
# .NET: Is both Client and Host OS version required? Or is "Platform OS" enough?
#
# -------------------------------------------------------------------
# Java specific environment variant
  - type: textarea
    id: java-build-environment
    attributes:
      label: "JAVA: Build environment"
      description: Build environment versions
      value: |
        Android Studio version: ...
        Android Build Tools version: ...
        Gradle version: ...
    validations:
# ? Should it be required?
      required: true

# Cocoa specific environment variant
  - type: textarea
    id: cocoa-build-environment
    attributes:
      label: "COCOA: Build environment"
      description: |
        Build environment versions
        In the [CONTRIBUTING guidelines](https://github.com/realm/realm-cocoa/blob/master/CONTRIBUTING.md#speeding-things-up-runner), you will find a script, which will help determining some of these versions.
# ? Is the script still correct and useful? It seems to output more than needed?
      value: |
        Xcode version: ...
        Dependency manager and version: ...
    validations:
      required: true

# JS specific environment variant
  - type: textarea
    id: JS-build-environment
    attributes:
      label: "JS: Build environment"
      description: Build environment versions
      value: |
        Which debugger for React Native: ...
    validations:
      required: true

# .NET only
  - type: dropdown
    id: app-type
    attributes:
      label: ".NET:  What type of application is this?"
      options:
        - Unity
        - Xamarin
        - WPF
        - Console/Server
        - Other
    validations:
      required: true
