name: Bug Report
description: Report a bug
labels: [T-Bug]
body:
  - type: dropdown
    id: frequency
    attributes:
      label: How frequently does the bug occur?
      options:
        - Once
        - Sometimes
        - Allways
    validations:
      required: true

  - type: dropdown
    id: repro
    attributes:
      label: Can you reproduce the bug?
      options:
        - Always
        - Sometimes
        - No
    validations:
      required: true
  
  - type: dropdown
    id: sync
    attributes:
      label: What SDK Sync flavour are you using?
      options:
        - Local Database only
        - Atlas Device Sync
        - Atlas App Services
    validations:
      required: true

  - type: dropdown
    id: flavour
    attributes:
      label: What SDK flavour are you using?
      options:
        - Local Database only
        - Atlas Device Sync
        - MongoDB Realm

  - type: dropdown
    id: encryption
    attributes:
      label: Are you using Encryption?
      options:
        - 'Yes'
        - 'No'

# .NET only
  - type: dropdown
    id: app-type
    attributes:
      label: ".NET:  What type of application is this?"
      options:
        - Unity
        - Xamarin
        - WPF
        - Console/Server
        - Other
    validations:
      required: false
