name: Bug Report
description: Report a bug
labels: [T-Bug]
body:
  - type: checkboxes
    id: frequency
    attributes:
      label: How frequently does the bug occur?
      multiple: false
      options:
        - label: -- select --
        - label: Once
        - label: Sometimes
        - label: Always
    validations:
      required: true

  - type: dropdown
    id: repro
    attributes:
      label: Can you reproduce the bug?
      options:
        - -- select --
        - Always
        - Sometimes
        - 'No'
    validations:
      required: true
  
  - type: dropdown
    id: services
    attributes:
      label: What Services are you using?
      options:
        - -- select --
        - Local Database only
        - Atlas Device Sync
        - 'Atlas App Services: Auth or Functions etc'
        - Both Atlas Device Sync and Atlas App Services
    validations:
      required: true

  - type: dropdown
    id: encryption
    attributes:
      label: Are you using Encryption?
      options:
        - -- select --
        - 'Yes'
        - 'No'
    validations:
      required: true
      
# .NET only
  - type: dropdown
    id: app-type
    attributes:
      label: "What type of application is this?"
      options:
        - -- select --
        - Unity
        - Xamarin
        - WPF
        - Console/Server
        - Other
    validations:
      required: true
