name: Bug Report
description: Report a bug
labels: [Bug]
body:
- type: markdown
  attributes:
    value: |
      Please provide as much detail as you can.
      Thanks in advance!
- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: Describe what you were expecting and what actually happened.     
    placeholder: Tell us what you see!
    value: "A bug happened!"
- type: textarea
  id: repro
  attributes:
    label: Reproduction steps
    description: "How do you trigger this bug? Please walk us through it step by step."
    value: |
      multi line text
      1.
      2.
      3.
      ...
    render: bash
- type: input
  id: version
  attributes:
    label: Version
    description: What version of the .NET SDK are you using?
- type: dropdown
  id: app-type
  attributes:
    label: What type of application is this?
    options:
      - Unity
      - Xamarin
- type: textarea
  id: logs
  attributes:
    label: Relevant log output
    description: Please copy and paste any relevant log output.
    render: shell
