name: Bug Report3
description: Report a bug 3 - With multi word label "How severe is it?"
labels: [T-Bug]
body:
- type: dropdown
  id: severity
  attributes:
    label: How severe is it?
    description: Please choose the severity of the impact of this issue.
    multiple: false
    options:
      - 'Low'
      - 'Medium'
      - 'High'
      - 'Urgent'
      - 'Other'
  validations:
    required: true
