name: Update version in repo B

on:
  release:
    types: [created]

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo A
        uses: actions/checkout@v3
        with:
          repository: bmunkholm/Test
          ref: ${{ github.event.release.target_commitish }}
      
      - name: Get release version
        run: echo "::set-output name=version::${{ github.event.release.tag_name }}"

      - name: Checkout repo B
        uses: actions/checkout@v3
        with:
          repository: bmunkholm/test2
          ref: main

      - name: Update version file
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          echo "${{ steps.get_version.outputs.version }}" > version.txt
          git add version.txt
          git commit -m "Update version to ${{ steps.get_version.outputs.version }}"
          git push
      
      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          title: "Update version to ${{ steps.get_version.outputs.version }}"
          commit-message: "Update version to ${{ steps.get_version.outputs.version }}"
          branch: "update-version"
          base: "main"
          labels: "auto-generated"
          body: "This pull request updates the version in version.txt to ${{ steps.get_version.outputs.version }}."
